In [84]:
import numpy as np
import pandas as pd

In [85]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn import datasets

In [86]:
wine=datasets.load_wine()
wine

{'DESCR': 'Wine Data Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- 1) Alcohol\n \t\t- 2) Malic acid\n \t\t- 3) Ash\n\t\t- 4) Alcalinity of ash  \n \t\t- 5) Magnesium\n\t\t- 6) Total phenols\n \t\t- 7) Flavanoids\n \t\t- 8) Nonflavanoid phenols\n \t\t- 9) Proanthocyanins\n\t\t- 10)Color intensity\n \t\t- 11)Hue\n \t\t- 12)OD280/OD315 of diluted wines\n \t\t- 13)Proline\n        \t- class:\n                - class_0\n                - class_1\n                - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80   

In [87]:
x=wine.data
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [88]:
y=wine.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [89]:
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [90]:
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [91]:
algo=LinearDiscriminantAnalysis()

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [94]:
#from sklearn.preprocessing import StandardScaler

In [95]:
#scaler=StandardScaler()

In [96]:
#xtrain=scaler.fit_transform(xtrain,ytrain)

In [97]:
#xtest=scaler.transform(xtest)

In [98]:
algo.fit(xtrain,ytrain)

C:\anaconda\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [99]:
pred=algo.predict(xtest)

In [100]:
from sklearn.metrics import confusion_matrix,classification_report

In [101]:
print(classification_report(ytest,pred))
print(confusion_matrix(ytest,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      0.95      0.98        21
          2       0.91      1.00      0.95        10

avg / total       0.98      0.98      0.98        45

[[14  0  0]
 [ 0 20  1]
 [ 0  0 10]]


In [102]:
from sklearn.decomposition import PCA
algo2=PCA()
xtrain=algo2.fit_transform(xtrain)
xtest=algo2.transform(xtest)

In [103]:
algo2.explained_variance_ratio_

array([9.97884296e-01, 1.93543704e-03, 1.01155887e-04, 5.20487568e-05,
       1.18048876e-05, 7.79108140e-06, 3.27668784e-06, 1.66598483e-06,
       1.16800720e-06, 7.06316057e-07, 3.40867508e-07, 2.22307287e-07,
       8.57515558e-08])