In [4]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [6]:
import seaborn as sns

In [7]:
iris=datasets.load_iris()

In [11]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
df['target']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
x=df.iloc[:,:df.shape[1]-1]
y=df.iloc[:,-1]

In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [14]:
algo=SVC()

In [15]:
algo.fit(xtrain,ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
pred=algo.predict(xtest)

In [17]:
from sklearn.metrics import classification_report,confusion_matrix

In [18]:
print(confusion_matrix(ytest,pred))
print(classification_report(ytest,pred))

[[ 9  0  0]
 [ 0 17  1]
 [ 0  0 11]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       1.00      0.94      0.97        18
          2       0.92      1.00      0.96        11

avg / total       0.98      0.97      0.97        38



In [19]:
from sklearn.grid_search import GridSearchCV

In [20]:
d={'C':[0.01,0.1,1,10,100,1000],'gamma':[10,1,0.1,0.01,0.001,0.0001]}

In [32]:
g_algo=GridSearchCV(SVC(),d)
g_algo.fit(xtrain,ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.01, 0.1, 1, 10, 100, 1000], 'gamma': [10, 1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [34]:
g_algo.best_params_

{'C': 1, 'gamma': 1}

In [35]:
g_algo.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [36]:
gpred=g_algo.predict(xtest)

In [37]:
print(confusion_matrix(ytest,gpred))
print(classification_report(ytest,gpred))

[[ 9  0  0]
 [ 0 16  2]
 [ 0  0 11]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       1.00      0.89      0.94        18
          2       0.85      1.00      0.92        11

avg / total       0.96      0.95      0.95        38

